# Testing for .NET 9
name: .NET 9 (Latest) Build & Test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

permissions:
  contents: read

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      dotnet-version: '9.0.x'
      target-framework: 'net9.0'